# Generated by Django 5.2.8 on 2025-11-17 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventario",
            "0005_formulario_alter_cliente_rut_alter_cliente_telefono_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="correo",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="telefono",
            field=models.CharField(
                max_length=9,
                validators=[
                    django.core.validators.RegexValidator(
                        message="El teléfono debe contener solo dígitos (máx. 9).",
                        regex="^\\d{1,9}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="formulario",
            name="correo",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="formulario",
            name="telefono",
            field=models.CharField(
                max_length=9,
                validators=[
                    django.core.validators.RegexValidator(
                        message="El teléfono debe contener solo dígitos (máx. 9).",
                        regex="^\\d{1,9}$",
                    )
                ],
            ),
        ),
    ]
