# Generated by Django 5.2.6 on 2025-09-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_ventas_alter_producto_id_detalleventa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=13)),
                ('nombre', models.CharField(max_length=32)),
                ('correo', models.CharField(max_length=32)),
                ('telefono', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
