# Generated by Django 5.2.6 on 2025-09-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=32)),
                ('correo', models.CharField(max_length=32)),
                ('telefono', models.DecimalField(decimal_places=0, max_digits=9)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.DecimalField(decimal_places=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='rut',
            field=models.CharField(max_length=10),
        ),
    ]
